export const RARE_WORDS = [
  { word: "concinnity", definition: "Elegance and harmony of arrangement; studied symmetry of style.", synonyms: ["harmony", "symmetry", "elegance", "neatness", "balance", "proportion", "polish"] },
  { word: "succedaneum", definition: "A substitute, especially for a medicine.", synonyms: ["substitute", "replacement", "surrogate", "stand-in", "proxy", "alternative", "stopgap"] },
  { word: "thaumaturge", definition: "A worker of wonders; a miracle-worker.", synonyms: ["miracle-worker", "magician", "wonder-worker", "wizard", "sorcerer", "conjurer"] },
  { word: "operose", definition: "Involving great labor or effort; tedious.", synonyms: ["laborious", "toilsome", "arduous", "tedious", "painstaking", "burdensome", "onerous", "wearisome"] },
  { word: "famulus", definition: "A private secretary or attendant, especially of a magician or scholar.", synonyms: ["assistant", "attendant", "secretary", "amanuensis", "apprentice", "helper", "factotum"] },
  { word: "logorrhea", definition: "Excessive and often incoherent talkativeness; a flow of words far beyond the speaker's needs.", synonyms: ["verbosity", "garrulity", "loquacity", "wordiness", "prolixity", "babble", "verbiage"] },
  { word: "etiolate", definition: "To make pale and weak (of plants, by deprivation of light); to enfeeble or render lifeless.", synonyms: ["pale", "weaken", "blanch", "drain", "enfeeble", "wither", "fade", "exhaust"] },
  { word: "estivate", definition: "To spend a hot or dry period in a prolonged state of torpor or dormancy.", synonyms: ["dormant", "summer-sleep", "lie-low", "rest"] },
  { word: "scapegrace", definition: "A mischievous or wayward person, especially a young man; a rascal.", synonyms: ["rascal", "rogue", "scoundrel", "ne'er-do-well", "good-for-nothing", "miscreant", "wastrel"] },
  { word: "prelapsarian", definition: "Of or relating to the time before the Fall of Man; innocent and untroubled.", synonyms: ["innocent", "edenic", "primal", "pristine", "untroubled", "blissful", "pure", "unspoiled"] },
  { word: "rebarbative", definition: "Repellent; unattractive; objectionable.", synonyms: ["repellent", "off-putting", "unattractive", "forbidding", "grim", "unpleasant", "repulsive"] },
  { word: "inanition", definition: "Exhaustion caused by lack of nourishment; emptiness; lethargy.", synonyms: ["exhaustion", "emptiness", "depletion", "starvation", "lassitude", "torpor", "vacuity"] },
  { word: "panurgic", definition: "Ready or able to do anything; resourceful in any task.", synonyms: ["resourceful", "versatile", "capable", "all-around", "adaptable", "ingenious"] },
  { word: "supererogation", definition: "The act of doing more than is required by duty.", synonyms: ["surplus-virtue", "extra-effort", "going-beyond"] },
  { word: "irrefragable", definition: "Impossible to deny or refute; incontrovertible.", synonyms: ["incontrovertible", "irrefutable", "indisputable", "undeniable", "unassailable", "conclusive", "indubitable"] },
  { word: "comminatory", definition: "Threatening; denunciatory; relating to threats of punishment.", synonyms: ["threatening", "denunciatory", "menacing", "minatory", "intimidating", "fulminatory"] },
  { word: "haruspex", definition: "An ancient Roman priest who practiced divination by inspecting the entrails of sacrificial animals.", synonyms: ["soothsayer", "diviner", "augur", "prophet", "seer", "oracle"] },
  { word: "wamble", definition: "To feel nausea; to move unsteadily; to roll or churn (of the stomach).", synonyms: ["churn", "roll", "lurch", "stagger", "totter", "reel", "writhe"] },
  { word: "epicene", definition: "Having characteristics of both sexes or no sex; (of a noun) referring to either sex without change of form.", synonyms: ["androgynous", "unisex", "ambiguous", "neutral", "ambisexual"] },
  { word: "pellucidity", definition: "Translucent clearness; transparency, often of style or expression.", synonyms: ["transparency", "clarity", "lucidity", "limpidness", "intelligibility", "translucence"] },
  { word: "merdivorous", definition: "Feeding on dung.", synonyms: ["dung-eating", "coprophagous", "scatophagous"] },
  { word: "objurgate", definition: "To rebuke severely; to scold sharply.", synonyms: ["rebuke", "scold", "berate", "chide", "censure", "upbraid", "reproach", "reprimand", "castigate"] },
  { word: "tergiversate", definition: "To make conflicting or evasive statements; to change one's loyalties.", synonyms: ["equivocate", "prevaricate", "waver", "vacillate", "hedge", "dodge", "evade", "shift"] },
  { word: "mountebank", definition: "A person who deceives others, especially in order to trick them out of money; a charlatan.", synonyms: ["charlatan", "fraud", "swindler", "imposter", "con artist", "quack", "huckster", "trickster"] },
  { word: "oneiric", definition: "Of or relating to dreams; dreamlike.", synonyms: ["dreamlike", "dreamy", "surreal", "visionary", "fantastic", "phantasmagoric"] },
  { word: "obtrude", definition: "To impose or force (something or oneself) on others without invitation.", synonyms: ["impose", "force", "thrust", "intrude", "press", "inflict", "interject"] },
  { word: "psephology", definition: "The statistical study of elections and voting.", synonyms: ["election-study", "polling", "electoral analysis", "political statistics"] },
  { word: "longanimity", definition: "Patient endurance of hardship, injuries, or offense.", synonyms: ["forbearance", "patience", "endurance", "tolerance", "fortitude", "long-suffering", "stoicism"] },
  { word: "eleemosynary", definition: "Of, relating to, or dependent on charity.", synonyms: ["charitable", "philanthropic", "benevolent", "almsgiving", "humanitarian", "altruistic"] },
  { word: "thrasonical", definition: "Boastful; vainglorious.", synonyms: ["boastful", "vainglorious", "bragging", "swaggering", "blustering", "self-important", "pompous"] },
  { word: "logomachy", definition: "An argument about words; a dispute carried on in mere words.", synonyms: ["wordplay", "quibble", "dispute", "altercation", "wrangle", "polemic"] },
  { word: "noctambulist", definition: "A sleepwalker.", synonyms: ["sleepwalker", "somnambulist", "night-walker"] },
  { word: "macilent", definition: "Lean; thin; emaciated.", synonyms: ["lean", "thin", "gaunt", "emaciated", "scrawny", "spare", "haggard"] },
  { word: "kakistocracy", definition: "Government by the worst people.", synonyms: ["misrule", "tyranny", "misgovernment", "corruption"] },
  { word: "selcouth", definition: "Strange, marvelous, unfamiliar.", synonyms: ["strange", "marvelous", "wondrous", "unfamiliar", "uncanny", "rare", "uncommon", "weird"] },
  { word: "caliginous", definition: "Misty; dim; obscure.", synonyms: ["misty", "dim", "dark", "obscure", "murky", "shadowy", "tenebrous", "foggy"] },
  { word: "philodox", definition: "A person fond of their own opinions; a dogmatist.", synonyms: ["dogmatist", "opinionated person", "ideologue", "doctrinaire"] },
  { word: "deipnosophist", definition: "A person skilled in dinner-table conversation.", synonyms: ["raconteur", "conversationalist", "wit", "talker"] },
  { word: "brumous", definition: "Foggy, misty; relating to winter mist.", synonyms: ["foggy", "misty", "wintry", "hazy", "murky", "vaporous"] },
  { word: "callipygian", definition: "Having shapely buttocks.", synonyms: ["shapely", "well-formed", "comely", "beautiful", "rounded", "voluptuous"] },
  { word: "sesquipedalian", definition: "Characterized by long words; given to using long words.", synonyms: ["long-winded", "polysyllabic", "verbose", "grandiloquent", "magniloquent", "ornate"] },
  { word: "petrichor", definition: "The pleasant earthy smell produced when rain falls on dry soil.", synonyms: ["earth-scent", "rain-smell"] },
  { word: "hugger-mugger", definition: "Confused, disorderly secrecy; muddle.", synonyms: ["confusion", "muddle", "secrecy", "concealment", "disorder", "chaos", "jumble", "mess"] },
  { word: "pleonasm", definition: "The use of more words than necessary to convey meaning.", synonyms: ["redundancy", "tautology", "verbosity", "wordiness", "circumlocution"] },
  { word: "scrimshank", definition: "To shirk one's duties or work; to malinger.", synonyms: ["shirk", "malinger", "skive", "slack", "evade", "dodge", "loaf"] },
  { word: "yclept", definition: "Called; named.", synonyms: ["named", "called", "designated", "termed", "known as"] },
  { word: "epigone", definition: "A less distinguished follower or imitator of a great artist or thinker.", synonyms: ["imitator", "follower", "disciple", "successor", "copyist", "derivative"] },
  { word: "bdelygmia", definition: "A rhetorical expression of hatred or abuse, often through a series of insults.", synonyms: ["invective", "tirade", "diatribe", "vilification", "vituperation", "abuse"] },
  { word: "mumpsimus", definition: "A traditional custom or notion adhered to even though shown to be unreasonable.", synonyms: ["error", "obstinacy", "stubbornness", "dogma", "fixation", "shibboleth"] },
  { word: "crepuscule", definition: "Twilight; the dim period at dawn or dusk.", synonyms: ["twilight", "dusk", "gloaming", "half-light", "evening", "nightfall"] },
  { word: "borborygmus", definition: "A rumbling or gurgling noise made by the movement of fluid and gas in the intestines.", synonyms: ["rumbling", "gurgling", "stomach-rumble", "growl", "grumble"] },
  { word: "ultracrepidarian", definition: "A person who gives opinions on subjects beyond their knowledge.", synonyms: ["know-it-all", "pretender", "dilettante", "smatterer", "pontificator"] },
  { word: "anfractuous", definition: "Winding, tortuous; full of twists and bends.", synonyms: ["winding", "tortuous", "sinuous", "convoluted", "circuitous", "meandering", "involved", "labyrinthine"] },
  { word: "velleity", definition: "A wish or inclination not strong enough to lead to action.", synonyms: ["whim", "wish", "inclination", "fancy", "desire", "yen", "impulse", "yearning"] },
  { word: "tatterdemalion", definition: "A person in tattered clothing; a ragged, beggarly person.", synonyms: ["ragamuffin", "beggar", "vagabond", "scarecrow", "urchin", "wretch"] },
  { word: "obnubilate", definition: "To darken, dim, or obscure as with a cloud.", synonyms: ["obscure", "cloud", "darken", "dim", "becloud", "befog", "shadow", "veil"] },
  { word: "psithurism", definition: "The sound of wind through trees or rustling leaves.", synonyms: ["rustling", "susurration", "whispering", "soughing", "murmur", "rustle"] },
  { word: "fugacious", definition: "Tending to disappear or vanish; fleeting.", synonyms: ["fleeting", "transient", "evanescent", "ephemeral", "passing", "momentary", "short-lived", "brief"] },
  { word: "tenebrous", definition: "Dark, shadowy, or obscure.", synonyms: ["dark", "shadowy", "gloomy", "obscure", "murky", "shadowy", "tenebrous", "foggy"] },
  { word: "rhabdomancy", definition: "The use of a divining rod, typically to find water or metal underground.", synonyms: ["dowsing", "divining", "water-witching", "divination"] },
  { word: "deliquesce", definition: "To become liquid, typically by absorbing moisture from the air.", synonyms: ["liquefy", "dissolve", "melt", "soften", "thaw", "fluidize"] },
  { word: "apricity", definition: "The warmth of the sun in winter.", synonyms: ["sun-warmth", "winter sun", "sunniness"] },
  { word: "agelast", definition: "A person who never laughs.", synonyms: ["sourpuss", "killjoy", "stoic", "puritan", "wet blanket"] },
  { word: "sycorax", definition: "A malevolent witch (literary, after Shakespeare's Tempest).", synonyms: ["witch", "crone", "hag", "sorceress", "enchantress"] },
  { word: "bowdlerize", definition: "To remove material considered improper or offensive from a text.", synonyms: ["censor", "expurgate", "sanitize", "edit", "clean up", "purge", "redact", "soften"] },
  { word: "vermicular", definition: "Resembling a worm in form or movement; wavy and twisting.", synonyms: ["wormlike", "winding", "twisting", "sinuous", "wavy", "serpentine", "meandering", "writhing"] },
  { word: "panoply", definition: "A complete or impressive collection of things; a splendid display.", synonyms: ["array", "collection", "assemblage", "spectacle", "display", "show", "range", "variety", "splendor"] },
  { word: "panegyric", definition: "A public speech or text in praise of someone or something.", synonyms: ["eulogy", "tribute", "encomium", "praise", "accolade", "homage", "paean", "commendation"] },
  { word: "ineluctable", definition: "Unable to be resisted or avoided; inescapable.", synonyms: ["inescapable", "inevitable", "unavoidable", "irresistible", "certain", "destined", "preordained", "fated"] },
  { word: "limn", definition: "To depict or describe in painting or words.", synonyms: ["depict", "portray", "describe", "render", "outline", "sketch", "delineate", "paint", "draw"] },
  { word: "redoubtable", definition: "Formidable; commanding respect through fear or admiration.", synonyms: ["formidable", "fearsome", "dreaded", "esteemed", "respected", "imposing", "powerful", "venerable", "awe-inspiring"] },
  { word: "pellucid", definition: "Translucently clear; easily understood.", synonyms: ["clear", "limpid", "transparent", "lucid", "translucent", "crystalline", "intelligible", "plain", "lucid"] },
  { word: "supercilious", definition: "Behaving as though one is superior to others.", synonyms: ["arrogant", "haughty", "disdainful", "condescending", "snobbish", "lofty", "patronizing", "imperious", "scornful"] },
  { word: "vicissitude", definition: "A change of circumstances or fortune, typically one that is unwelcome.", synonyms: ["change", "variation", "shift", "fluctuation", "alteration", "reversal", "twist", "ups and downs", "turn"] },
  { word: "vituperate", definition: "To blame or insult in strong, abusive language.", synonyms: ["berate", "revile", "abuse", "denounce", "censure", "castigate", "reproach", "excoriate", "upbraid"] },
  { word: "susurrus", definition: "A whispering, murmuring, or rustling sound.", synonyms: ["whisper", "rustle", "murmur", "hum", "soft sound", "psithurism", "sigh"] },
  { word: "asseverate", definition: "To declare or affirm solemnly.", synonyms: ["assert", "affirm", "declare", "maintain", "insist", "avow", "swear", "proclaim", "attest"] },
  { word: "minatory", definition: "Threatening; menacing.", synonyms: ["threatening", "menacing", "ominous", "intimidating", "warning", "baleful", "sinister", "forbidding"] },
  { word: "stentorian", definition: "Of a voice or person, extremely loud.", synonyms: ["loud", "thunderous", "booming", "resounding", "powerful", "carrying", "sonorous", "vociferous"] },
  { word: "argosy", definition: "A large merchant ship; a fleet of such ships; a rich supply.", synonyms: ["fleet", "ship", "treasure-trove", "wealth", "abundance", "store", "trove", "armada"] },
  { word: "puissant", definition: "Powerful; mighty.", synonyms: ["powerful", "mighty", "potent", "strong", "forceful", "formidable", "robust", "commanding"] },
  { word: "pulchritude", definition: "Physical beauty.", synonyms: ["beauty", "loveliness", "comeliness", "attractiveness", "handsomeness", "splendor", "fairness", "prettiness"] },
  { word: "halidom", definition: "A holy place; a holy thing; a sanctuary.", synonyms: ["sanctuary", "holy place", "shrine", "sacred relic", "haven", "asylum", "refuge"] },
  { word: "farrago", definition: "A confused mixture; a hotchpotch.", synonyms: ["jumble", "mixture", "medley", "mishmash", "hodgepodge", "miscellany", "potpourri", "assortment", "farrago"] },
  { word: "apophenia", definition: "The tendency to perceive meaningful connections or patterns where none exist.", synonyms: ["pattern-finding", "pareidolia", "conspiracism", "false-pattern recognition"] },
  { word: "petrify", definition: "To turn to stone; to paralyze with fear.", synonyms: ["terrify", "paralyze", "horrify", "stun", "freeze", "fossilize", "harden", "ossify"] },
  { word: "perspicuous", definition: "Clearly expressed and easy to understand.", synonyms: ["clear", "lucid", "transparent", "intelligible", "comprehensible", "plain", "explicit", "straightforward"] },
  { word: "spelean", definition: "Pertaining to caves; cave-dwelling.", synonyms: ["cavernous", "cave-like", "subterranean", "underground", "troglodytic"] },
  { word: "thaumaturgy", definition: "The performance of miracles or magic.", synonyms: ["magic", "miracle-working", "sorcery", "wizardry", "wonder-working", "conjuring", "enchantment"] },
  { word: "imbroglio", definition: "An extremely confused, complicated, or embarrassing situation.", synonyms: ["entanglement", "mess", "muddle", "predicament", "quandary", "complication", "scandal", "fiasco"] },
  { word: "scrivener", definition: "A clerk, copyist, or writer of legal documents.", synonyms: ["clerk", "copyist", "scribe", "writer", "amanuensis", "secretary", "stenographer"] },
  { word: "pulchritudinous", definition: "Physically beautiful, especially in a striking or grand way.", synonyms: ["beautiful", "gorgeous", "stunning", "lovely", "comely", "resplendent", "ravishing", "exquisite", "fair", "handsome"] },
  { word: "lacuna", definition: "A missing portion; a gap or hiatus, especially in a manuscript or argument.", synonyms: ["gap", "hiatus", "void", "blank", "omission", "absence", "hole", "interval", "missing piece"] },
  { word: "limerence", definition: "An involuntary, intense romantic longing for another person.", synonyms: ["infatuation", "crush", "obsession", "longing", "passion", "love-sickness", "yearning"] },
  { word: "quotidian", definition: "Of or occurring every day; ordinary.", synonyms: ["daily", "everyday", "ordinary", "routine", "commonplace", "mundane", "habitual", "customary", "usual"] },
  { word: "sepulchral", definition: "Pertaining to a tomb; dismal, gloomy, or hollow in sound.", synonyms: ["funereal", "gloomy", "dismal", "grave", "mournful", "cavernous", "hollow", "tomb-like", "macabre", "somber"] },
  { word: "vellichor", definition: "The strange wistfulness of used bookshops.", synonyms: ["nostalgia", "wistfulness", "melancholy", "longing", "saudade", "reverie"] },
  { word: "saudade", definition: "A Portuguese word for a profound, bittersweet longing for something absent.", synonyms: ["longing", "nostalgia", "yearning", "melancholy", "wistfulness", "hiraeth"] },
  { word: "hiraeth", definition: "A Welsh word for a deep longing for a home that may no longer exist or never was.", synonyms: ["homesickness", "longing", "nostalgia", "yearning", "saudade", "melancholy"] },
  // Additional high-difficulty words
  { word: "cacoethes", definition: "An uncontrollable urge to do something; a mania.", synonyms: ["mania", "compulsion", "urge", "craving", "itch", "obsession"] },
  { word: "enervate", definition: "To cause someone to feel drained of energy or vitality; weaken.", synonyms: ["exhaust", "fatigue", "weaken", "drain", "sap", "debilitate"] },
  { word: "garrulous", definition: "Excessively talkative, especially on trivial matters.", synonyms: ["talkative", "loquacious", "verbose", "chatty", "voluble"] },
  { word: "inchoate", definition: "Just begun and so not fully formed or developed; rudimentary.", synonyms: ["budding", "nascent", "developing", "embryonic", "immature"] },
  { word: "juxtapose", definition: "Place or deal with close together for contrasting effect.", synonyms: ["contrast", "collate", "compare", "sandwich", "side-by-side"] },
  { word: "mellifluous", definition: "Sweet or musical; pleasant to hear.", synonyms: ["melodious", "musical", "tuneful", "euphonious", "sweet-sounding"] },
  { word: "nefarious", definition: "Wicked or criminal.", synonyms: ["wicked", "evil", "sinful", "villainous", "heinous"] },
  { word: "obsequious", definition: "Obedient or attentive to an excessive or servile degree.", synonyms: ["servile", "fawning", "subservient", "sycophantic", "toadying"] },
  { word: "pernicious", definition: "Having a harmful effect, especially in a gradual or subtle way.", synonyms: ["harmful", "damaging", "deleterious", "detrimental", "malignant"] },
  { word: "recalcitrant", definition: "Having an obstinately uncooperative attitude toward authority or discipline.", synonyms: ["uncooperative", "intractable", "stubborn", "obstinate", "defiant"] },
  { word: "sycophant", definition: "A person who acts obsequiously toward someone important in order to gain advantage.", synonyms: ["toady", "flatterer", "yes-man", "bootlicker", "creep"] },
  { word: "ubiquitous", definition: "Present, appearing, or found everywhere.", synonyms: ["everywhere", "omnipresent", "pervasive", "rife", "universal"] },
  { word: "vacillate", definition: "Alternate or waver between different opinions or actions; be indecisive.", synonyms: ["waver", "dither", "hesitate", "teeter", "fluctuate"] },
  { word: "absquatulate", definition: "To leave abruptly.", synonyms: ["bolt", "flee", "decamp", "vamoose", "escape"] },
  { word: "pervicacious", definition: "Obstinate; stubborn.", synonyms: ["stubborn", "obstinate", "headstrong", "willful", "unyielding"] },
  { word: "suspiration", definition: "A long deep breath; a sigh.", synonyms: ["sigh", "breath", "gasp", "heave", "exhalation"] }
];
