export const RARE_WORDS = [
  { word: "accede", definition: "1. give in, agree to 2. take office", synonyms: ["give in", "agree to", "take office"] },
  { word: "acclaim", definition: "praise", synonyms: ["praise"] },
  { word: "acquiesce", definition: "give in", synonyms: ["give in"] },
  { word: "affable", definition: "friendly", synonyms: ["friendly"] },
  { word: "affected", definition: "1. influenced by something 2. artificial, trying to impress", synonyms: ["influenced", "artificial", "pretentious"] },
  { word: "affluent", definition: "wealthy", synonyms: ["wealthy"] },
  { word: "ailment", definition: "illness", synonyms: ["illness"] },
  { word: "ambivalence", definition: "mixed feelings", synonyms: ["mixed feelings", "uncertainty"] },
  { word: "amenable", definition: "1. cooperative, easily persuaded 2. receptive, responsive", synonyms: ["cooperative", "persuadable", "receptive", "responsive"] },
  { word: "animosity", definition: "hostility", synonyms: ["hostility"] },
  { word: "anomalous", definition: "not normal, unusual", synonyms: ["abnormal", "unusual", "atypical"] },
  { word: "antecedent", definition: "what came before", synonyms: ["precursor", "prior"] },
  { word: "antithesis", definition: "opposite", synonyms: ["opposite", "inverse"] },
  { word: "apathetic", definition: "lacking interest", synonyms: ["indifferent", "uninterested"] },
  { word: "apparatus", definition: "device, equipment", synonyms: ["device", "equipment", "gear"] },
  { word: "arbitrary", definition: "random", synonyms: ["random", "chance"] },
  { word: "archaic", definition: "old or old-fashioned", synonyms: ["old", "old-fashioned", "antiquated"] },
  { word: "assail", definition: "attack", synonyms: ["attack", "assault"] },
  { word: "assuage", definition: "1. relieve, soothe 2. satisfy", synonyms: ["relieve", "soothe", "satisfy"] },
  { word: "atrophy", definition: "waste away", synonyms: ["waste away", "wither"] },
  { word: "atypical", definition: "not normal", synonyms: ["abnormal", "unusual"] },
  { word: "augment", definition: "enlarge, increase", synonyms: ["enlarge", "increase"] },
  { word: "auspicious", definition: "favorable, promising", synonyms: ["favorable", "promising"] },
  { word: "aversion", definition: "dislike", synonyms: ["dislike", "hatred"] },
  { word: "banal", definition: "not original, common, boring", synonyms: ["unoriginal", "common", "boring"] },
  { word: "benevolent", definition: "generous", synonyms: ["generous", "kind"] },
  { word: "bog", definition: "marsh, swamp", synonyms: ["marsh", "swamp"] },
  { word: "buoyant", definition: "1. cheerful 2. floating 3. very active (in an economic context)", synonyms: ["cheerful", "floating", "active"] },
  { word: "buttress", definition: "support", synonyms: ["support", "reinforce"] },
  { word: "byzantine", definition: "excessively complex", synonyms: ["complex", "intricate"] },
  { word: "cajole", definition: "persuade", synonyms: ["persuade", "coax"] },
  { word: "callous", definition: "cruelly insensitive", synonyms: ["insensitive", "heartless"] },
  { word: "capacity", definition: "ability", synonyms: ["ability", "capability"] },
  { word: "catalyst", definition: "something that triggers an event", synonyms: ["trigger", "stimulus"] },
  { word: "caustic", definition: "1. bitter and sarcastic 2. acidic", synonyms: ["sarcastic", "bitter", "acidic"] },
  { word: "cerebral", definition: "intellectual", synonyms: ["intellectual", "analytical"] },
  { word: "charismatic", definition: "charming", synonyms: ["charming", "alluring"] },
  { word: "circumscribe", definition: "restrict, limit", synonyms: ["restrict", "limit", "confine"] },
  { word: "circumvent", definition: "overcome an obstacle", synonyms: ["bypass", "evade"] },
  { word: "cite", definition: "1. quote as evidence 2. mention as an example", synonyms: ["quote", "mention"] },
  { word: "combustible", definition: "able to catch fire easily", synonyms: ["flammable", "explosive"] },
  { word: "compatible", definition: "1. able to co-exist peacefully, well-suited 2. consistent", synonyms: ["harmonious", "consistent", "well-suited"] },
  { word: "compile", definition: "assemble, collect", synonyms: ["assemble", "collect", "gather"] },
  { word: "comply", definition: "go along with rules", synonyms: ["obey", "conform"] },
  { word: "comprehensive", definition: "thorough", synonyms: ["thorough", "complete", "exhaustive"] },
  { word: "conducive", definition: "favorable to, likely to bring about a certain outcome", synonyms: ["favorable", "helpful"] },
  { word: "congenial", definition: "pleasant", synonyms: ["pleasant", "agreeable"] },
  { word: "conscientious", definition: "careful, hardworking", synonyms: ["careful", "hardworking", "diligent"] },
  { word: "constraint", definition: "restriction, limitation", synonyms: ["restriction", "limitation"] },
  { word: "consummate", definition: "1. (verb) complete, make perfect 2. (adjective) highly skilled, perfect", synonyms: ["perfect", "complete", "skilled"] },
  { word: "contemporary", definition: "1. living or occurring at the same time 2. occurring in the present", synonyms: ["simultaneous", "modern", "present"] },
  { word: "contemptuous", definition: "scornful, disrespectful", synonyms: ["scornful", "disrespectful"] },
  { word: "concontingency", definition: "1. possibility 2. unforeseen event", synonyms: ["possibility", "chance"] },
  { word: "convoluted", definition: "complicated, twisted", synonyms: ["complicated", "twisted", "complex"] },
  { word: "criterion", definition: "standard by which things are judged or measured", synonyms: ["standard", "measure", "benchmark"] },
  { word: "cursory", definition: "quick, hurried, not thorough", synonyms: ["quick", "hurried", "shallow"] },
  { word: "deficit", definition: "lack, shortage", synonyms: ["lack", "shortage", "shortfall"] },
  { word: "definitive", definition: "absolute, authoritative", synonyms: ["absolute", "authoritative", "final"] },
  { word: "demure", definition: "overly modest, shy", synonyms: ["modest", "shy", "reserved"] },
  { word: "denounce", definition: "declare to be wrong, criticize", synonyms: ["criticize", "condemn"] },
  { word: "depose", definition: "1. remove from power 2. testify or give evidence (in a legal context)", synonyms: ["oust", "testify"] },
  { word: "deprecate", definition: "disapprove of, criticize", synonyms: ["criticize", "disapprove"] },
  { word: "derivative", definition: "not original", synonyms: ["unoriginal", "imitative"] },
  { word: "derogatory", definition: "insulting, disrespecting", synonyms: ["insulting", "offensive"] },
  { word: "destitute", definition: "poor", synonyms: ["poor", "impoverished"] },
  { word: "deter", definition: "prevent, discourage", synonyms: ["prevent", "discourage", "hinder"] },
  { word: "detrimental", definition: "damaging, harmful", synonyms: ["harmful", "damaging"] },
  { word: "devoid", definition: "lacking", synonyms: ["lacking", "empty", "bare"] },
  { word: "diligent", definition: "hardworking", synonyms: ["hardworking", "industrious"] },
  { word: "diplomatic", definition: "1. having to do with foreign relations 2. tactful, sensitive, polite", synonyms: ["tactful", "polite", "sensitive"] },
  { word: "dire", definition: "urgent, dreadful", synonyms: ["urgent", "dreadful", "severe"] },
  { word: "discount", definition: "1. reduce in price 2. ignore, disregard", synonyms: ["reduce", "ignore", "disregard"] },
  { word: "discourse", definition: "discussion", synonyms: ["discussion", "conversation", "debate"] },
  { word: "discredit", definition: "harm someone's reputation", synonyms: ["disgrace", "defame"] },
  { word: "discrepancy", definition: "difference, mismatch", synonyms: ["difference", "mismatch", "variance"] },
  { word: "discriminating", definition: "selective, having refined taste", synonyms: ["selective", "discerning"] },
  { word: "disseminate", definition: "scatter or spread widely", synonyms: ["spread", "scatter", "distribute"] },
  { word: "domestic", definition: "relating to the home or the home country", synonyms: ["home", "local", "native"] },
  { word: "dominant", definition: "most important or powerful", synonyms: ["powerful", "primary", "leading"] },
  { word: "dormant", definition: "not active", synonyms: ["inactive", "asleep"] },
  { word: "eclectic", definition: "from a variety of sources", synonyms: ["diverse", "varied"] },
  { word: "efface", definition: "erase", synonyms: ["erase", "wipe out"] },
  { word: "effervesce", definition: "bubble, fizz", synonyms: ["bubble", "fizz"] },
  { word: "eloquence", definition: "flowing and persuasive speech or writing", synonyms: ["fluency", "articulacy"] },
  { word: "elude", definition: "escape from, avoid", synonyms: ["escape", "avoid", "evade"] },
  { word: "embitter", definition: "cause someone to feel bitter", synonyms: ["sour", "anger"] },
  { word: "empirical", definition: "based on observation and experimentation", synonyms: ["observed", "factual", "experimental"] },
  { word: "encompass", definition: "include, surround", synonyms: ["include", "surround", "contain"] },
  { word: "endorse", definition: "approve, support", synonyms: ["approve", "support", "back"] },
  { word: "enigma", definition: "mystery", synonyms: ["mystery", "puzzle", "riddle"] },
  { word: "equanimity", definition: "calmness", synonyms: ["calmness", "composure"] },
  { word: "equitable", definition: "fair, even-handed", synonyms: ["fair", "just", "impartial"] },
  { word: "erroneous", definition: "incorrect", synonyms: ["incorrect", "wrong", "false"] },
  { word: "evince", definition: "show clearly", synonyms: ["show", "reveal", "manifest"] },
  { word: "exacting", definition: "demanding, having severe requirements", synonyms: ["demanding", "strict", "harsh"] },
  { word: "exasperate", definition: "annoy", synonyms: ["annoy", "frustrate", "irritate"] },
  { word: "excise", definition: "remove", synonyms: ["remove", "cut out"] },
  { word: "explicit", definition: "fully expressed, leaving nothing implied", synonyms: ["clear", "direct", "unambiguous"] },
  { word: "exploit", definition: "1. (verb) benefit unfairly from something 2. (noun) bold or heroic deed", synonyms: ["utilize", "abuse", "feat", "deed"] },
  { word: "facile", definition: "1. shallow, simplistic 2. effortless", synonyms: ["simplistic", "shallow", "easy", "effortless"] },
  { word: "facilitate", definition: "help, make easier", synonyms: ["help", "assist", "ease"] },
  { word: "faction", definition: "a small group within a larger group", synonyms: ["group", "sect", "clique"] },
  { word: "fallacy", definition: "mistaken belief, faulty reasoning", synonyms: ["error", "misconception"] },
  { word: "fastidious", definition: "careful, painstaking", synonyms: ["careful", "meticulous"] },
  { word: "fathom", definition: "1. (verb) understand 2. a unit of depth, usually measuring water", synonyms: ["understand", "comprehend"] },
  { word: "flag", definition: "1. (noun) symbol of a country or institution 2. (verb) point out, signal, draw attention to 3. (verb) become tired or weak", synonyms: ["signal", "mark", "weaken", "fade"] },
  { word: "florid", definition: "1. having a red or flushed face 2. flowery, elaborate", synonyms: ["flushed", "elaborate", "ornate"] },
  { word: "folly", definition: "foolishness", synonyms: ["foolishness", "idiocy"] },
  { word: "furtive", definition: "sneaky", synonyms: ["sneaky", "secretive", "sly"] },
  { word: "generic", definition: "general, not specific", synonyms: ["general", "common"] },
  { word: "germinate", definition: "begin or cause to grow", synonyms: ["grow", "sprout"] },
  { word: "glacial", definition: "1. icy, related to glaciers 2. cold, unfriendly 3. extremely slow", synonyms: ["icy", "cold", "slow"] },
  { word: "gravity", definition: "seriousness", synonyms: ["seriousness", "importance"] },
  { word: "hail", definition: "1. (noun) pellets of ice 2. (verb) rain down with force 3. (verb) signal, greet, call out 4. (verb) praise", synonyms: ["greet", "praise", "cheer"] },
  { word: "harbor", definition: "1. (noun) safe place or shelter, particularly for boats 2. (verb) keep or hold in mind 3. (verb) give a home to, shelter, or hide someone", synonyms: ["shelter", "port", "cherish", "hide"] },
  { word: "hedonist", definition: "someone driven by pleasure", synonyms: ["pleasure-seeker", "sybarite"] },
  { word: "heresy", definition: "belief that goes against the established opinion", synonyms: ["dissidence", "blasphemy"] },
  { word: "hierarchy", definition: "ranking, classification", synonyms: ["ranking", "ladder", "grading"] },
  { word: "hospitable", definition: "welcoming, friendly", synonyms: ["welcoming", "friendly", "cordial"] },
  { word: "hypothesis", definition: "theory, guess", synonyms: ["theory", "guess", "premise"] },
  { word: "iconoclast", definition: "someone who attacks traditional beliefs", synonyms: ["rebel", "maverick", "dissenter"] },
  { word: "ideology", definition: "system of ideas, way of thinking", synonyms: ["beliefs", "creed", "philosophy"] },
  { word: "idiosyncrasy", definition: "unique personal trait", synonyms: ["quirk", "eccentricity"] },
  { word: "impeccable", definition: "perfect, flawless", synonyms: ["perfect", "flawless", "spotless"] },
  { word: "impetuous", definition: "impulsive, spontaneous", synonyms: ["impulsive", "spontaneous", "rash"] },
  { word: "impetus", definition: "motivation", synonyms: ["motivation", "stimulus", "momentum"] },
  { word: "incarnate", definition: "1. possessing a concrete, material form 2. in the flesh", synonyms: ["embodied", "manifested"] },
  { word: "incontrovertible", definition: "definitive, unable to be denied", synonyms: ["indisputable", "undeniable"] },
  { word: "incorrigible", definition: "incapable of being corrected or improved", synonyms: ["unreformable", "incurable"] },
  { word: "incredulous", definition: "disbelieving, skeptical", synonyms: ["skeptical", "disbelieving", "doubtful"] },
  { word: "indiscriminate", definition: "unselective, random", synonyms: ["random", "unselective", "haphazard"] },
  { word: "indisposed", definition: "1. ill 2. unwilling", synonyms: ["ill", "unwell", "unwilling", "reluctant"] },
  { word: "induce", definition: "1. bring about, cause 2. arrive at a conclusion by logical reasoning", synonyms: ["cause", "persuade", "prompt"] },
  { word: "inert", definition: "not moving or active", synonyms: ["inactive", "motionless", "still"] },
  { word: "inherent", definition: "innate, inborn, natural", synonyms: ["innate", "natural", "intrinsic"] },
  { word: "inhibit", definition: "hold back, restrain, prevent", synonyms: ["restrain", "prevent", "hinder"] },
  { word: "innocuous", definition: "harmless", synonyms: ["harmless", "safe"] },
  { word: "innovate", definition: "make something new, change, create", synonyms: ["create", "invent"] },
  { word: "insidious", definition: "sneaky, stealthy, treacherous", synonyms: ["sneaky", "treacherous", "stealthy"] },
  { word: "insular", definition: "1. related to or similar to an island 2. narrow-minded, isolated", synonyms: ["isolated", "narrow-minded", "parochial"] },
  { word: "integrity", definition: "1. honesty, dignity 2. completeness", synonyms: ["honesty", "wholeness", "rectitude"] },
  { word: "inundate", definition: "flood, overwhelm", synonyms: ["flood", "overwhelm", "swamp"] },
  { word: "irony", definition: "difference between what is expected and what actually happens", synonyms: ["paradox", "sarcasm"] },
  { word: "laborious", definition: "involving hard work", synonyms: ["hard", "difficult", "arduous"] },
  { word: "lofty", definition: "1. tall 2. majestic, noble 3. arrogant", synonyms: ["tall", "noble", "arrogant"] },
  { word: "lucid", definition: "clear, easily understood", synonyms: ["clear", "coherent"] },
  { word: "lurid", definition: "sensational, shocking", synonyms: ["shocking", "sensational", "gory"] },
  { word: "malign", definition: "1. (adjective) evil 2. (verb) criticize, speak ill of", synonyms: ["evil", "criticize", "slander"] },
  { word: "mar", definition: "hurt someone's appearance", synonyms: ["spoil", "ruin", "damage"] },
  { word: "meander", definition: "wander", synonyms: ["wander", "drift", "ramble"] },
  { word: "mercenary", definition: "1. (adjective) motivated by money 2. (noun) soldier hired to fight for a foreign country", synonyms: ["greedy", "hired-soldier"] },
  { word: "mercurial", definition: "unpredictable, inconsistent", synonyms: ["unpredictable", "volatile", "fickle"] },
  { word: "mitigate", definition: "make less serious, reduce", synonyms: ["reduce", "alleviate", "lessen"] },
  { word: "muted", definition: "quiet, soft", synonyms: ["quiet", "soft", "subdued"] },
  { word: "myopic", definition: "1. nearsighted 2. unimaginative", synonyms: ["nearsighted", "shortsighted"] },
  { word: "nebulous", definition: "vague, cloudy", synonyms: ["vague", "cloudy", "hazy"] },
  { word: "nonchalance", definition: "lack of concern", synonyms: ["indifference", "coolness"] },
  { word: "notorious", definition: "famous for something bad", synonyms: ["infamous"] },
  { word: "novelty", definition: "1. newness, originality 2. a trinket or toy", synonyms: ["newness", "originality", "trinket"] },
  { word: "odoriferous", definition: "having a strong or unpleasant smell", synonyms: ["smelly", "fragrant", "stinky"] },
  { word: "opaque", definition: "1. not transparent 2. hard to understand", synonyms: ["cloudy", "obscure", "unclear"] },
  { word: "opportunist", definition: "a person who takes advantage of opportunities, often unethically", synonyms: ["exploiter", "timeserver"] },
  { word: "orthodox", definition: "conservative, traditional", synonyms: ["traditional", "conventional"] },
  { word: "oversight", definition: "mistake", synonyms: ["mistake", "error", "omission"] },
  { word: "parochial", definition: "1. relating to church 2. narrow-minded, unsophisticated", synonyms: ["narrow-minded", "provincial"] },
  { word: "particular", definition: "1. specific, individual 2. fussy, demanding", synonyms: ["specific", "fussy", "picky"] },
  { word: "partisan", definition: "1. supporter of a party or a cause 2. someone who is prejudiced towards a certain cause", synonyms: ["supporter", "biased", "prejudiced"] },
  { word: "patronize", definition: "1. support financially 2. act superior, look down on", synonyms: ["support", "condescend"] },
  { word: "peremptory", definition: "bossy, commanding", synonyms: ["bossy", "commanding", "dictatorial"] },
  { word: "perennial", definition: "long-lasting, continual", synonyms: ["continual", "lasting", "enduring"] },
  { word: "perfidious", definition: "untrustworthy, disloyal", synonyms: ["disloyal", "treacherous"] },
  { word: "perverse", definition: "1. unacceptable, unreasonable 2. unnatural, abnormal", synonyms: ["unreasonable", "contrary", "abnormal"] },
  { word: "pigment", definition: "substance that gives color", synonyms: ["color", "dye", "tint"] },
  { word: "plebeian", definition: "common citizen", synonyms: ["commoner", "proletarian"] },
  { word: "poignant", definition: "emotionally touching", synonyms: ["touching", "moving", "affecting"] },
  { word: "pragmatic", definition: "practical", synonyms: ["practical", "realistic"] },
  { word: "precipitate", definition: "cause a sudden outcome", synonyms: ["trigger", "hasten"] },
  { word: "precocious", definition: "having early development in maturity and intelligence", synonyms: ["advanced", "mature", "gifted"] },
  { word: "prescribe", definition: "1. recommend, advise 2. command", synonyms: ["recommend", "advise", "order"] },
  { word: "presumption", definition: "1. assumption, guess 2. boldness, disrespect", synonyms: ["assumption", "boldness", "audacity"] },
  { word: "pretense", definition: "1. make-believe, fake 2. false claim", synonyms: ["fake", "charade", "pretext"] },
  { word: "prevalent", definition: "widespread", synonyms: ["widespread", "common", "rampant"] },
  { word: "proclivity", definition: "natural tendency", synonyms: ["tendency", "leaning", "inclination"] },
  { word: "procure", definition: "get or provide", synonyms: ["obtain", "acquire", "get"] },
  { word: "profane", definition: "1. not sacred or religious 2. showing disrespect for religion", synonyms: ["secular", "irreverent", "blasphemous"] },
  { word: "prohibitive", definition: "1. forbidding or restricting 2. excessively high in price", synonyms: ["restrictive", "expensive", "exorbitant"] },
  { word: "prolific", definition: "1. productive, creative, fertile 2. plentiful", synonyms: ["productive", "fruitful", "abundant"] },
  { word: "prospective", definition: "likely or expected to become", synonyms: ["potential", "expected", "future"] },
  { word: "quagmire", definition: "1. complex, difficult situation 2. bog or swamp", synonyms: ["predicament", "swamp", "marsh"] },
  { word: "qualified", definition: "1. competent, able 2. limited", synonyms: ["capable", "limited", "conditional"] },
  { word: "quash", definition: "1. reject 2. put down, suppress", synonyms: ["suppress", "crush", "reject"] },
  { word: "radical", definition: "extreme", synonyms: ["extreme", "drastic"] },
  { word: "recourse", definition: "the act of turning to someone or something for assistance", synonyms: ["resort", "remedy", "aid"] },
  { word: "rectify", definition: "put right, correct", synonyms: ["correct", "amend", "fix"] },
  { word: "regressive", definition: "backward-looking, becoming less advanced", synonyms: ["backward", "retrograde"] },
  { word: "rejuvenate", definition: "make young again", synonyms: ["revitalize", "refresh"] },
  { word: "remission", definition: "reduction or decrease, particularly of a debt or medical symptoms", synonyms: ["abatement", "respite", "reduction"] },
  { word: "remote", definition: "distant, far", synonyms: ["distant", "far", "isolated"] },
  { word: "renounce", definition: "reject, abandon", synonyms: ["reject", "abandon", "relinquish"] },
  { word: "repudiate", definition: "reject entirely, deny", synonyms: ["deny", "disown", "reject"] },
  { word: "repugnant", definition: "offensive, disgusting", synonyms: ["offensive", "disgusting", "repulsive"] },
  { word: "resign", definition: "1. give in, surrender 2. step down from a position", synonyms: ["surrender", "quit", "abdicate"] },
  { word: "rhetoric", definition: "persuasive speech or writing", synonyms: ["oratory", "eloquence", "discourse"] },
  { word: "rudimentary", definition: "1. basic 2. undeveloped, incomplete", synonyms: ["basic", "elementary", "primitive"] },
  { word: "sanction", definition: "1. (noun) penalty for disobeying a law 2. (verb) punish, impose a penalty 3. (verb) formally approve", synonyms: ["penalty", "punish", "approve", "authorize"] },
  { word: "sanguine", definition: "cheerfully confident, optimistic", synonyms: ["optimistic", "confident", "cheerful"] },
  { word: "satire", definition: "sarcastic imitation", synonyms: ["parody", "mockery", "irony"] },
  { word: "saturate", definition: "soak, make completely full", synonyms: ["soak", "drench", "imbue"] },
  { word: "scintillating", definition: "lively, effervescent", synonyms: ["sparkling", "brilliant", "lively"] },
  { word: "scope", definition: "1. range 2. opportunity, possibility", synonyms: ["range", "extent", "opportunity"] },
  { word: "sensational", definition: "amazing, shocking, scandalous", synonyms: ["amazing", "shocking", "scandalous"] },
  { word: "servile", definition: "submissive, overly willing to please", synonyms: ["submissive", "fawning", "slavish"] },
  { word: "shopworn", definition: "worn out, trite", synonyms: ["trite", "hackneyed", "worn-out"] },
  { word: "simile", definition: "comparison", synonyms: ["comparison", "analogy"] },
  { word: "solicitous", definition: "expressing care or concern, often too much", synonyms: ["concerned", "caring", "anxious"] },
  { word: "sparse", definition: "lacking, rare", synonyms: ["scant", "thin", "meager"] },
  { word: "spate", definition: "outbreak of similar events happening one after another", synonyms: ["series", "flurry", "wave"] },
  { word: "spurn", definition: "reject, turn down", synonyms: ["reject", "scorn", "decline"] },
  { word: "stagnant", definition: "not moving", synonyms: ["still", "motionless", "inactive"] },
  { word: "stark", definition: "harsh, plain", synonyms: ["harsh", "plain", "bare", "austere"] },
  { word: "staunch", definition: "strong, loyal", synonyms: ["loyal", "firm", "steadfast"] },
  { word: "stock", definition: "standard, usual, automatic", synonyms: ["standard", "usual", "routine"] },
  { word: "strain", definition: "1. (verb) stress, force, make an excessive effort 2. (noun) excessive stress, effort, or force 3. (verb) separate solids from a liquid", synonyms: ["stress", "effort", "filter", "stretch"] },
  { word: "stupefy", definition: "amaze", synonyms: ["stun", "amaze", "astonish"] },
  { word: "subjugate", definition: "conquer, dominate, control", synonyms: ["conquer", "dominate", "enslave"] },
  { word: "subordinate", definition: "lower in rank, inferior", synonyms: ["inferior", "lower", "secondary"] },
  { word: "subservient", definition: "1. obedient, yielding 2. less important", synonyms: ["obedient", "compliant", "inferior"] },
  { word: "subtle", definition: "not obvious", synonyms: ["understated", "faint", "delicate"] },
  { word: "supine", definition: "1. lying on one's back 2. not resisting", synonyms: ["horizontal", "passive", "inactive"] },
  { word: "susceptible", definition: "easily influenced or affected", synonyms: ["vulnerable", "prone", "sensitive"] },
  { word: "sustain", definition: "1. strengthen, support 2. maintain, carry on 3. experience, suffer", synonyms: ["support", "maintain", "endure"] },
  { word: "synthesis", definition: "combination of elements or ideas", synonyms: ["combination", "blend", "amalgam"] },
  { word: "tangent", definition: "1. different or irrelevant line of thought 2. a line that touches a curve at a point (in math)", synonyms: ["digression", "divergence"] },
  { word: "tempestuous", definition: "stormy", synonyms: ["stormy", "turbulent", "wild"] },
  { word: "tenacious", definition: "stubborn, determined", synonyms: ["stubborn", "determined", "persistent"] },
  { word: "thrive", definition: "grow, develop, prosper", synonyms: ["prosper", "flourish", "grow"] },
  { word: "transcend", definition: "go beyond, rise above", synonyms: ["surpass", "exceed"] },
  { word: "trite", definition: "unoriginal, common", synonyms: ["unoriginal", "banal", "cliché"] },
  { word: "unorthodox", definition: "not traditional", synonyms: ["unconventional", "unusual"] },
  { word: "unprecedented", definition: "without any previous example", synonyms: ["unparalleled", "new", "novel"] },
  { word: "usurp", definition: "seize power without authority", synonyms: ["seize", "takeover", "arrogate"] },
  { word: "vicarious", definition: "felt indirectly by imagining someone else's experiences", synonyms: ["indirect", "surrogate"] },
  { word: "vindicate", definition: "clear someone of blame, prove to be right", synonyms: ["exonerate", "acquit", "justify"] },
  { word: "virulent", definition: "1. poisonous 2. bitter, harsh, hostile", synonyms: ["toxic", "hostile", "bitter"] },
  { word: "vitiate", definition: "spoil, destroy", synonyms: ["spoil", "corrupt", "ruin"] },
  { word: "vocation", definition: "career", synonyms: ["career", "calling", "profession"] },
  { word: "vulnerable", definition: "susceptible, exposed", synonyms: ["exposed", "susceptible", "defenseless"] },
  { word: "wane", definition: "lessen, become weaker", synonyms: ["decline", "diminish", "fade"] },
  { word: "wary", definition: "cautious", synonyms: ["cautious", "careful", "watchful"] },
  { word: "wry", definition: "having a clever or grim sense of humor", synonyms: ["droll", "sardonic", "dry"] }
];
